export const APPWRITE_URL = import.meta.env.VITE_APPWRITE_URL;
export const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID;
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;
export const APPWRITE_STORAGE_ID = import.meta.env.VITE_APPWRITE_STORAGE_ID;
export const APPWRITE_COLLECTION_DEALS = import.meta.env
  .VITE_APPWRITE_COLLECTION_DEALS;
export const APPWRITE_COLLECTION_CUSTOMERS = import.meta.env
  .VITE_APPWRITE_COLLECTION_CUSTOMERS;
export const APPWRITE_COLLECTION_COMMENTS = import.meta.env
  .VITE_APPWRITE_COLLECTION_COMMENTS;
